# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_folder: c:\lvl2\lvl2.workshop

init:
  - git config --global core.autocrlf input

environment:
  matrix:
  # node.js
  - nodejs_version: 0.10
  - nodejs_version: 0.11
  # io.js
  - nodejs_version: 1.0

  allow_failures:
    # currently unsupported build environments by atom-shell
    - nodejs_version: 0.11

    - nodejs_version: 1.0
    

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - npm install -g grunt-cli
  - npm install
  - grunt build:shell

test_script:
  - node --version
  - npm --version

build: off