# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

#version: "0.0.1-ci.{build}-{branch}"
version: "0.0.1-ci.{build}"

clone_folder: c:\lvl2\lvl2.workshop

init:
  - git config --global core.autocrlf input

# Do not build on tags (GitHub only)
skip_tags: true

environment:
# Build matrices
  matrix:
  # node.js
  - nodejs_version: 0.10
  #- nodejs_version: 0.11
  # io.js
  #- nodejs_version: 1.0

# Matrix Configurations
matrix:
  allow_failures:
    # currently unsupported build environments by atom-shell
    - nodejs_version: 0.11
    - nodejs_version: 1.0


platform:
  - x86

cache:
  # Default directory (as defined in package.json) of the git repo
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\.git -> package.json
  # Submodules, to speed up the bootstrapping process
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\atom -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\chromium_src -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\docs -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\external_binaries -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\node_modules -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\script -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\spec -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\tools -> package.json
  - C:\Users\appveyor\.lvl2.workshop\atom-shell\vendor -> package.json
  # npm cache
  - C:\Users\appveyor\AppData\Roaming\npm-cache

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install -g grunt-cli
  - npm install
  - npm config set msvs_version 2013 --global
  - npm config list
  - cmd: PATH
  - grunt --verbose --debug shell:build

test_script:
  - node --version
  - npm --version

build: off