# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

#version: "0.0.1-ci.{build}-{branch}"
version: "0.0.1-ci.{build}"

clone_folder: c:\lvl2\lvl2.workshop

init:
  - git config --global core.autocrlf input

# Do not build on tags (GitHub only)
skip_tags: true

environment:
# Build matrices
  matrix:
  # node.js
  - nodejs_version: 0.10
  #- nodejs_version: 0.11
  # io.js
  #- nodejs_version: 1.0

# Matrix Configurations
matrix:
  allow_failures:
    # currently unsupported build environments by atom-shell
    - nodejs_version: 0.11
    - nodejs_version: 1.0


platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - node --version
  - npm --version
  - npm install -g grunt-cli
  - npm install
  - npm config list
  - dir C:\Program Files (x86)\MSBuild\12.0\bin\
  #- grunt --verbose shell:build

test_script:
  - node --version
  - npm --version

build: off